variable "project_name"          { type = string }
variable "vpc_id"                { type = string }
variable "ami"                   { type = string }
variable "instance_type"         { type = string }
variable "key_pair_name"         { type = string }
variable "private_app_subnet_ids"{ type = list(string) }
variable "alb_sg_id"             { type = string }
variable "target_group_arn"      { type = string }
variable "min_size"              { type = number }
variable "max_size"              { type = number }
variable "desired_size"          { type = number }
variable "my_ip"                 { type = string }
